'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FullTextSearch

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''txtQuery control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtQuery As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''QueryFieldValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents QueryFieldValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''lblResultCount control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblResultCount As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lblQuerySummary control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lblQuerySummary As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''DataList1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents DataList1 As Global.System.Web.UI.WebControls.DataList
End Class
